export const appCopy = {
  ar: {
    meta: {
      locale: "ar-SA",
      dir: "rtl",
      switchLanguage: "English",
      switchThemeLight: "فاتح",
      switchThemeDark: "داكن",
    },
    brand: {
      login: "تسجيل الدخول",
      logout: "تسجيل الخروج",
      subtitle: "منصة تشغيلية لإدارة التحديات والأفكار والمراجعة",
    },
    auth: {
      title: "منصة الابتكار - تسجيل الدخول",
      subtitle: "تسجيل دخول للمستخدمين المسجلين أو إنشاء حساب جديد لتقديم الأفكار على التحديات.",
      loginTab: "دخول",
      registerTab: "تسجيل",
      name: "الاسم الكامل",
      email: "البريد الإلكتروني",
      password: "كلمة المرور",
      organization: "الجهة / المنظمة",
      accountType: "نوع الحساب",
      publicUser: "مستخدم عام",
      partnerEntity: "جهة شريكة",
      submitLogin: "دخول",
      submitRegister: "إنشاء حساب",
      demoTitle: "حسابات الوزارة التجريبية",
      demoSubtitle: "هذه الحسابات تمثل الأدوار التشغيلية المذكورة في وثائق العمل.",
      publicHint: "الحسابات العامة يمكنها التسجيل وتقديم الأفكار فقط.",
    },
    nav: {
      home: "الرئيسية",
      challenges: "التحديات",
      submitIdea: "تقديم فكرة",
      createChallenge: "إنشاء تحدٍ",
      reviews: "مراجعة الأفكار",
      myIdeas: "أفكاري",
      chatbot: "المساعد الذكي",
      admin: "لوحة الإدارة",
    },
    roles: {
      admin: "مدير النظام",
      innovation_director: "مدير إدارة الابتكار",
      innovation_staff: "موظف إدارة الابتكار",
      innovation_expert: "خبير ابتكار",
      sector_owner: "مالك التحدي من القطاع",
      public_user: "مستخدم عام",
      partner_entity: "جهة شريكة",
    },
    home: {
      title: "منصة تشغيلية كاملة",
      subtitle: "تطبيق متصل بقاعدة بيانات ويدعم الأدوار، المصادقة، إنشاء التحديات، تقديم الأفكار، والمراجعة الداخلية.",
      cards: {
        challenges: "التحديات النشطة",
        ideas: "إجمالي الأفكار",
        reviews: "إجمالي المراجعات",
        pending: "أفكار بانتظار القرار",
      },
      recentIdeas: "آخر الأفكار",
      noIdeas: "لا توجد أفكار حديثة بعد.",
    },
    challenges: {
      title: "التحديات",
      subtitle: "جميع التحديات المخزنة في النظام مع معلومات النطاق والملكية وعدد الأفكار.",
      owner: "الجهة المالكة",
      createdBy: "أنشئ بواسطة",
      ideaCount: "عدد الأفكار",
      scope: "النطاق",
      objectives: "الأهداف",
    },
    createChallenge: {
      title: "إنشاء تحدٍ جديد",
      subtitle: "متاح فقط لمستخدمي الوزارة المخولين بطرح التحديات.",
      challengeTitle: "عنوان التحدي",
      summary: "ملخص التحدي",
      scope: "نطاق التحدي",
      objectives: "الأهداف",
      ownerDepartment: "القطاع / الإدارة المالكة",
      submit: "حفظ التحدي",
    },
    submitIdea: {
      title: "تقديم فكرة",
      subtitle: "اختر تحديًا قائمًا ثم قدم فكرة قابلة للمراجعة من قبل مستخدمي الوزارة.",
      challenge: "التحدي",
      titleField: "عنوان الفكرة",
      summary: "ملخص الفكرة",
      value: "القيمة المقترحة",
      plan: "خطة التنفيذ",
      submit: "إرسال الفكرة",
    },
    myIdeas: {
      title: "أفكاري",
      subtitle: "كل الأفكار التي قدمتها مع حالة المراجعة الحالية.",
      empty: "لا توجد أفكار مقدمة بعد.",
    },
    reviews: {
      title: "مراجعة الأفكار",
      subtitle: "قائمة الأفكار المرفوعة للتقييم من قبل أدوار الوزارة المعتمدة.",
      decision: "القرار",
      notes: "ملاحظات المراجع",
      approve: "اعتماد",
      reject: "رفض",
      revise: "طلب تعديل",
      pilot: "جاهز للتجربة",
      submit: "حفظ المراجعة",
      empty: "لا توجد أفكار بانتظار المراجعة.",
    },
    admin: {
      title: "لوحة الإدارة",
      subtitle: "مؤشرات النظام، المستخدمون، التحديات، وآخر الأفكار.",
      users: "المستخدمون",
      recentChallenges: "التحديات",
      recentIdeas: "الأفكار",
    },
    chatbot: {
      title: "المساعد الذكي",
      subtitle: "اسأل عن تحدٍ معين، اطلب نطاقًا احترافيًا، أو جهز مسودة فكرة قبل الإرسال.",
      placeholder: "اكتب سؤالك هنا...",
      send: "إرسال",
      loading: "جارٍ إعداد الرد...",
      empty: "مرحبًا، يمكنني مساعدتك في صياغة نطاق تحدٍ أو مقترح فكرة بشكل مهني.",
    },
    actions: {
      refresh: "تحديث",
      updateIdea: "تحديث الفكرة",
    },
    status: {
      open: "مفتوح",
      closed: "مغلق",
      submitted: "مقدم",
      under_review: "قيد المراجعة",
      approved: "معتمد",
      rejected: "مرفوض",
      revision_requested: "مطلوب تعديل",
      pilot_ready: "جاهز للتجربة",
    },
    messages: {
      welcome: "مرحبًا",
    },
  },
  en: {
    meta: {
      locale: "en-US",
      dir: "ltr",
      switchLanguage: "العربية",
      switchThemeLight: "Light",
      switchThemeDark: "Dark",
    },
    brand: {
      login: "Login",
      logout: "Logout",
      subtitle: "Operational platform for challenges, ideas, and internal review",
    },
    auth: {
      title: "Innovation Platform Sign In",
      subtitle: "Log in as an existing user or register a new account to submit ideas against ministry challenges.",
      loginTab: "Login",
      registerTab: "Register",
      name: "Full Name",
      email: "Email Address",
      password: "Password",
      organization: "Organization",
      accountType: "Account Type",
      publicUser: "Public User",
      partnerEntity: "Partner Entity",
      submitLogin: "Sign In",
      submitRegister: "Create Account",
      demoTitle: "Seeded Ministry Accounts",
      demoSubtitle: "These demo users represent the operating roles referenced in the work documents.",
      publicHint: "Public registrations can submit ideas, while ministry users manage challenges and reviews.",
    },
    nav: {
      home: "Home",
      challenges: "Challenges",
      submitIdea: "Submit Idea",
      createChallenge: "Create Challenge",
      reviews: "Review Queue",
      myIdeas: "My Ideas",
      chatbot: "AI Chatbot",
      admin: "Admin",
    },
    roles: {
      admin: "Platform Admin",
      innovation_director: "Innovation Director",
      innovation_staff: "Innovation Staff",
      innovation_expert: "Innovation Expert",
      sector_owner: "Sector Challenge Owner",
      public_user: "Public User",
      partner_entity: "Partner Entity",
    },
    home: {
      title: "Full Working Innovation Platform",
      subtitle: "A role-based application with database-backed authentication, challenge management, idea intake, and internal review workflows.",
      cards: {
        challenges: "Active challenges",
        ideas: "Total ideas",
        reviews: "Total reviews",
        pending: "Ideas awaiting decision",
      },
      recentIdeas: "Recent Ideas",
      noIdeas: "No recent ideas yet.",
    },
    challenges: {
      title: "Challenges",
      subtitle: "All challenges stored in the system, including scope, ownership, and live idea counts.",
      owner: "Owner Department",
      createdBy: "Created By",
      ideaCount: "Idea Count",
      scope: "Scope",
      objectives: "Objectives",
    },
    createChallenge: {
      title: "Create Challenge",
      subtitle: "Available only to authorized ministry users.",
      challengeTitle: "Challenge Title",
      summary: "Challenge Summary",
      scope: "Challenge Scope",
      objectives: "Objectives",
      ownerDepartment: "Owner Department",
      submit: "Save Challenge",
    },
    submitIdea: {
      title: "Submit Idea",
      subtitle: "Choose an active challenge and send an idea for ministry review.",
      challenge: "Challenge",
      titleField: "Idea Title",
      summary: "Idea Summary",
      value: "Value Proposition",
      plan: "Implementation Plan",
      submit: "Submit Idea",
    },
    myIdeas: {
      title: "My Ideas",
      subtitle: "Every idea you have submitted, together with its current review status.",
      empty: "You have not submitted any ideas yet.",
    },
    reviews: {
      title: "Review Queue",
      subtitle: "Ideas submitted for ministry-side review based on the assigned role.",
      decision: "Decision",
      notes: "Reviewer Notes",
      approve: "Approve",
      reject: "Reject",
      revise: "Request Revision",
      pilot: "Pilot Ready",
      submit: "Save Review",
      empty: "There are no ideas waiting for review.",
    },
    admin: {
      title: "Admin Dashboard",
      subtitle: "System metrics, users, challenges, and the latest submitted ideas.",
      users: "Users",
      recentChallenges: "Challenges",
      recentIdeas: "Ideas",
    },
    chatbot: {
      title: "AI Chatbot",
      subtitle: "Ask about a specific challenge, request a professional scope, or draft an idea submission before sending it.",
      placeholder: "Type your question here...",
      send: "Send",
      loading: "Preparing the response...",
      empty: "Hello. I can help you frame a challenge scope or shape an idea in a more professional way.",
    },
    actions: {
      refresh: "Refresh",
      updateIdea: "Update Idea",
    },
    status: {
      open: "Open",
      closed: "Closed",
      submitted: "Submitted",
      under_review: "Under review",
      approved: "Approved",
      rejected: "Rejected",
      revision_requested: "Revision requested",
      pilot_ready: "Pilot ready",
    },
    messages: {
      welcome: "Welcome",
    },
  },
};
